### ISSUE TITLE
Не хватает 3-го параметра

### ISSUE THREAD

**Issue by yaroslav-synapse** [synapse-studio/cmlservice#3]
cmlservice/src/Protocol/CmlImport.php строка 21
`return self::processData($migrations, $cmlid);`
Тут нужен 3 параметр.

Думаю лучше сделать вот так:
`public static function processData($migrations, $cmlid, $debug = false) {`
Вместо
`public static function processData($migrations, $cmlid, $debug) {`

**Comment by politsin** [comment]
fixed https://github.com/synapse-studio/cmlservice/commit/9daf99ddeee03c10a933623837d5ca35467b9620
